name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ "**" ]
  schedule:
    # Daily at 04:52
    - cron: '52 4 * * *'

jobs:
  ci:
    name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
          - name: Windows
            runs-on: windows-latest
          - name: macOS
            runs-on: macos-latest
        python:
          - name: CPython 2.7
            action: 2.7
          - name: CPython 3.5
            action: 3.5
          - name: CPython 3.6
            action: 3.6
          - name: CPython 3.7
            action: 3.7
          - name: CPython 3.8
            action: 3.8
          - name: CPython 3.9
            action: 3.9
          - name: PyPy 2.7
            action: pypy-2.7
          - name: PyPy 3.6
            action: pypy-3.6
          - name: PyPy 3.7
            action: pypy-3.7

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - name: Run the action
      uses: ./
      with:
        output-path: output_pre.log

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
        path: output_pre.log

    - name: Test
      shell: bash
      run: |
        python test.py --path output_pre.log

    - name: Install attrs
      shell: bash
      run: |
        python -m pip install attrs==20.3.0

    - name: Run the action with attrs installed
      uses: ./
      with:
        output-path: output_post.log

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
        path: output_post.log

    - name: Test
      shell: bash
      run: |
        python test.py --path output_post.log --package attrs 20.3.0

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: This
        shell: python
        run: |
          import this
